### PR TITLE
Correct spelling errors in Core module

### PR DESCRIPTION
**Pull request by SyntacticKitsune**
So this is something I've been wanting to do for a while. Basically, I've used the visitor API I added to Furblorb semi-recently in order to run hunspell over every piece of English text in Core (and also the other modules, not that anyone can tell.) Anyway, so I've used this to correct a bunch of typos across Core (with one even outside a string table!). I can also now say that the longest onomatopoeia award goes to `TOWN_PIT_O_CARSON_VICTORY` for "grrooooorrrgle". (~~Thank you for coming to my TED talk.~~)

Side note: the base branch is `master` since this PR doesn't feel like a format 21 thing (but I can change that if necessary).

### CODE REVIEW

**Review by pileofwolves — APPROVED** [review]
Good catches. It's funny how some of these are really obviously wrong, like 'coak', and it's so easy to just not see it while playtesting. _Inconspicuous_, if you will.

I agree that this commit should be merged to master, not a feature branch.

Funny enough, I have actually considered, multiple times, to integrate a spell checker into the editor. Never really got around to it, in part because I dislike pulling in 3rd party libraries. Maybe I'll have to just bite the bullet on this one though, it _would_ undeniably be a useful feature.

**Comment by SyntacticKitsune** [comment]
> It's funny how some of these are obviously wrong, like 'coak', and it's so easy to just not see it while playtesting

Exactly -- I've played through the game at least twice and I think the only one I caught was "entrace" in the 'taur dining' scene. It's amazing how easy it is to tune out grammatical errors, especially if you're not expecting them.

> Funny enough, I have actually considered, multiple times, to integrate a spell checker into the editor. Never really got around to it, in part because I dislike pulling in 3rd party libraries. Maybe I'll have to just bite the bullet on this one though, it *would* undeniably be a useful feature.

So to elaborate a bit on my spell-checking adventures (since I think that's relevant here), I've finally gotten around to making a proper hunspell dictionary for all the -- what exactly do we call these? Furry jargon? -- but anyway, one of the nicer features of this dictionary is support for variable-width onomatopoeia, since that tends to show up everywhere (and was a major problem with my previous approach).

If you want I can give you a copy of this dictionary (there's actually two -- one for the words, one for the names of places and characters) when it's finished which can be plugged into hunspell alongside the `en_US` and `en_GB` dictionaries (which I suppose I need to find the sources for, since "a package installed alongside some other one" isn't terribly useful). Then adding spell-checking is mostly a matter of hooking hunspell up to some text fields (very draw the rest of the owl I know).

One extra thing for if spell-checking ever gets added to the editor: there's gonna need to be support for at least one user dictionary, so that no one has to live with words-that-are-actually-words being considered wrong (although relatively common ones could probably be contributed to Finmer's dictionary). (Since occasionally Eclipse -- the IDE I use for Java development and ironically what I've been using for creating commits to this repository -- highlights things that are actual words as misspellings, and then I have to add them to the user dictionary. I think I'm up to 300 some entries now?)

**Comment by pileofwolves** [comment]
> variable-width onomatopoeia

Heh. I'm sorry-not-sorry for all the grroorrgles.

> If you want I can give you a copy of this dictionary

Sure, feel free. I don't know if/when I'll actually get around to it, but like I said it's been something that has been on the wishlist for a while. I'm actually considering taking some time to make some improvements to the scene editor, among those ideas for patching that you and others suggested a while ago. Might pick this up then.

> there's gonna need to be support for at least one user dictionary

Yeah, especially in a fantasy setting, made-up words and names are somewhat common and there should be a user dictionary feature for that.

> I have just now become aware of aspell

Will keep in mind, thanks for the tip.

**Comment by SyntacticKitsune** [comment]
[Here](https://gist.github.com/SyntacticKitsune/0136d8c77c7972244dee1b32d9c2b2b2)'s the dictionary I've created. (There's only one because I merged the two dictionaries together -- I figure there's no need to have them separate.)

There's some comments in the `.aff` (affix) file for both files, since the `.dic` file doesn't support comments in any form. The dictionary contains most, but not all, of the words I'm filtering out of my spell-checking program, which includes things like drunk Zosk or substitutions such as "newpredaliaspossessive3p" (okay I made that substitution up) since these aren't exactly valid words. Anyway, the dictionary is very likely missing things that either don't show up anywhere in the game (e.g. "pudgy") or that were somehow caught by other dictionaries (such as some character or place names). But fortunately it's pretty easy to add new words to the dictionary.

In other news, I guess I'm now all out of PRs to make (unless you'd like smaller PNGs) so it's probably time for me to finalize and post that feature request post. Those will all be author-facing, unlike the furball stuff. (In other words, actually interesting features others may be able to use, rather than technical discussions that are only interesting if you've maintained at least one (1) game engine.)

**Comment by pileofwolves** [comment]
I've downloaded your dictionary; if I do end up going with hunspell, I'll definitely use these as a starting point. Thanks for taking the time to look into that - and thanks again for all your time going into these PRs, as well as Furblorb. (I never really expected there to be any interest in this codebase at all, much less have someone write their own tools for it, what in the world haha.) It's safe to say you left the furball file format in a markedly better place than how you found it, eh?

At this time I don't really think having a PNG auto-compressor is worth the trouble. I'll continue using compression techniques for my own modules and assets, but for user-created modules, I expect the savings to be fairly minuscule - by and large GZIP is the largest space saver anyway.

If you have feature requests for more 'involved' editor tools or game features, I'd definitely be interested in hearing your ideas / use cases for them :)

**Pull request merged**
